"""Write requirements.lock: runtime deps of pyproject.toml with the versions installed
in the current (tested) virtualenv, transitively, extras included.

Run from backend/ after `make test` passes: .venv/bin/python scripts/lock_deps.py
The Docker image installs exactly these versions (FR-003, TT-07).
"""
import sys
import tomllib
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

HEADER = """\
# Generated by scripts/lock_deps.py from the tested virtualenv — do not edit by hand.
# Runtime dependencies only; the Docker image installs exactly these versions.
"""


def resolve(roots: list[str]) -> dict[str, str]:
    pins: dict[str, str] = {}
    seen: set[tuple[str, tuple[str, ...]]] = set()
    stack = [Requirement(r) for r in roots]
    while stack:
        req = stack.pop()
        key = (canonicalize_name(req.name), tuple(sorted(req.extras)))
        if key in seen:
            continue
        seen.add(key)
        try:
            dist = distribution(req.name)
        except PackageNotFoundError:
            sys.exit(f"{req.name} is not installed in this virtualenv")
        pins[canonicalize_name(req.name)] = dist.version
        envs = [{"extra": e} for e in (req.extras or {""})]
        for raw in dist.requires or []:
            dep = Requirement(raw)
            if dep.marker is None or any(dep.marker.evaluate(e) for e in envs):
                stack.append(dep)
    return pins


def main() -> None:
    root = Path(__file__).parent.parent
    deps = tomllib.loads((root / "pyproject.toml").read_text())["project"]["dependencies"]
    pins = resolve(deps)
    lines = [f"{name}=={pins[name]}" for name in sorted(pins)]
    (root / "requirements.lock").write_text(HEADER + "\n".join(lines) + "\n")
    print(f"requirements.lock: {len(lines)} packages")


if __name__ == "__main__":
    main()
