"""external contract v1.0 — registry, portfolio link, bases, work proposals, deliveries (ADR-024)

Existing data: a delivery recorded in Task.delivery names its proposal explicitly and becomes
a Delivery row; a manual recipient acceptance has no binding to an exact delivery and is kept
as a historical record without guessing its version. Tasks, packages, results and reviews
are not touched; no bases are invented, so no existing task becomes blocked.

Revision ID: d8f2a6c4e1b9
Revises: c1e8a5b2f6d4
Create Date: 2026-09-30 22:50:26.431465

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8f2a6c4e1b9'
down_revision: Union[str, Sequence[str], None] = 'c1e8a5b2f6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_providers',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('acquisition', sa.String(length=20), nullable=False),
    sa.Column('namespaces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fact_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_training', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('external_objects',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('ext_id', sa.String(length=500), nullable=False),
    sa.Column('locator', sa.String(length=2000), nullable=True),
    sa.Column('current_revision', sa.String(length=500), nullable=True),
    sa.Column('revision_state', sa.String(length=30), nullable=False),
    sa.Column('state_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['external_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'namespace', 'type', 'ext_id')
    )
    op.create_table('external_snapshots',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness', sa.String(length=20), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor', sa.String(length=1000), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['external_providers.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_events',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=500), nullable=False),
    sa.Column('contract_version', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('revision', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['external_providers.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'event_id')
    )
    op.create_table('external_identity_aliases',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('ext_id', sa.String(length=500), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['external_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'namespace', 'type', 'ext_id')
    )
    op.create_table('external_revisions',
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.String(length=500), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asserted_by', sa.String(length=500), nullable=True),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supersedes', sa.String(length=500), nullable=True),
    sa.Column('superseded_by', sa.String(length=500), nullable=True),
    sa.Column('is_revocation', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['external_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_id', 'revision')
    )
    op.create_index(op.f('ix_external_revisions_object_id'), 'external_revisions', ['object_id'], unique=False)
    op.create_table('project_portfolio_links',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('office_project_object_id', sa.Uuid(), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=False),
    sa.Column('regulation_object_id', sa.Uuid(), nullable=True),
    sa.Column('regulation_revision', sa.String(length=500), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('is_training', sa.Boolean(), nullable=False),
    sa.Column('enabled_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['office_project_object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulation_object_id'], ['external_objects.id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('office_project_object_id')
    )
    op.create_table('task_bases',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('meaning', sa.String(length=300), nullable=True),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'object_id', 'role')
    )
    op.create_index(op.f('ix_task_bases_task_id'), 'task_bases', ['task_id'], unique=False)
    op.create_table('task_blockers',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_blockers_task_id'), 'task_blockers', ['task_id'], unique=False)
    op.create_table('work_proposals',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('work_kind', sa.String(length=30), nullable=False),
    sa.Column('basis_object_id', sa.Uuid(), nullable=False),
    sa.Column('work_scope_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('updated_since_decision', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['basis_object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['work_proposals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stage', 'work_kind', 'basis_object_id', 'work_scope_key')
    )
    op.create_table('impact_assessments',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('basis_id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('old_revision', sa.String(length=500), nullable=False),
    sa.Column('new_revision', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=500), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['basis_id'], ['task_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_task_id'), 'impact_assessments', ['task_id'], unique=False)
    op.create_table('work_proposal_versions',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('basis_revision', sa.String(length=500), nullable=False),
    sa.Column('verification_plan_object_id', sa.Uuid(), nullable=True),
    sa.Column('verification_plan_revision', sa.String(length=500), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('result_scope', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('registered_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['external_events.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['work_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verification_plan_object_id'], ['external_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'basis_revision'),
    sa.UniqueConstraint('proposal_id', 'version')
    )
    op.create_index(op.f('ix_work_proposal_versions_proposal_id'), 'work_proposal_versions', ['proposal_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('work_package_id', sa.Uuid(), nullable=True),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('recipient_object_id', sa.Uuid(), nullable=True),
    sa.Column('ref', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['result_proposals.id'], ),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_object_id'], ['external_objects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_task_id'), 'deliveries', ['task_id'], unique=False)
    op.create_table('recipient_acceptances',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('work_package_id', sa.Uuid(), nullable=True),
    sa.Column('recipient', sa.String(length=500), nullable=False),
    sa.Column('usage_scope', sa.String(length=500), nullable=True),
    sa.Column('accepted_by', sa.String(length=500), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authority', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('ref', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('fact_revision_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('historical', sa.Boolean(), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.ForeignKeyConstraint(['fact_revision_id'], ['external_revisions.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['result_proposals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_package_id'], ['work_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipient_acceptances_task_id'), 'recipient_acceptances', ['task_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        INSERT INTO deliveries (id, task_id, proposal_id, work_package_id, target, ref, note, proposed_by,
                                created_at, updated_at)
        SELECT gen_random_uuid(), t.id, p.id, p.work_package_id, t.delivery->>'target', t.delivery->>'ref',
               t.delivery->>'note', COALESCE((t.delivery->>'proposed_by')::uuid, t.reporter_id),
               COALESCE((t.delivery->>'proposed_at')::timestamptz, now()), now()
        FROM tasks t JOIN result_proposals p ON p.id = (t.delivery->>'proposal_id')::uuid
        WHERE t.delivery IS NOT NULL AND t.delivery->>'target' IS NOT NULL
    """)
    op.execute("""
        UPDATE tasks t SET delivery = t.delivery || jsonb_build_object('delivery_id', d.id::text)
        FROM deliveries d WHERE d.task_id = t.id AND t.delivery IS NOT NULL
    """)
    op.execute("""
        INSERT INTO recipient_acceptances (id, task_id, recipient, accepted_by, accepted_at, source, ref, note,
                                           status, historical, recorded_by, created_at, updated_at)
        SELECT gen_random_uuid(), t.id, COALESCE(t.delivery->>'target', '—'),
               t.recipient_acceptance->>'accepted_by', (t.recipient_acceptance->>'accepted_at')::timestamptz,
               t.recipient_acceptance->>'source', t.recipient_acceptance->>'ref', t.recipient_acceptance->>'note',
               'accepted', true, (t.recipient_acceptance->>'recorded_by')::uuid,
               COALESCE((t.recipient_acceptance->>'recorded_at')::timestamptz, now()), now()
        FROM tasks t
        WHERE t.recipient_acceptance IS NOT NULL AND t.recipient_acceptance->>'accepted_by' IS NOT NULL
          AND t.recipient_acceptance->>'accepted_at' IS NOT NULL AND t.recipient_acceptance->>'source' IS NOT NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipient_acceptances_task_id'), table_name='recipient_acceptances')
    op.drop_table('recipient_acceptances')
    op.drop_index(op.f('ix_deliveries_task_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_work_proposal_versions_proposal_id'), table_name='work_proposal_versions')
    op.drop_table('work_proposal_versions')
    op.drop_index(op.f('ix_impact_assessments_task_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_table('work_proposals')
    op.drop_index(op.f('ix_task_blockers_task_id'), table_name='task_blockers')
    op.drop_table('task_blockers')
    op.drop_index(op.f('ix_task_bases_task_id'), table_name='task_bases')
    op.drop_table('task_bases')
    op.drop_table('project_portfolio_links')
    op.drop_index(op.f('ix_external_revisions_object_id'), table_name='external_revisions')
    op.drop_table('external_revisions')
    op.drop_table('external_identity_aliases')
    op.drop_table('external_events')
    op.drop_table('external_snapshots')
    op.drop_table('external_objects')
    op.drop_table('external_providers')
    # ### end Alembic commands ###
